### ISSUE TITLE
可以修改字体名称？

### ISSUE THREAD

**Issue by iPyCode** [edward-p/Consolas-with-Yahei#1]
你好，作者！
本来想装你修改的这个字体的，但发现会覆盖系统自带的consola。
你可以修改下字体的名称吗？

ps：被consola中文奇怪的显示困扰中~

**Comment by edward-p** [comment]
试过了，果断不行，如果你确实不想覆盖字体的话就使用[YaHei-Consolas-Hybrid-1.12](https://github.com/fengjianyun/YaHei-Consolas-Hybrid-1.12)（这个版本反引号角度没问题）

**Comment by h1orz** [comment]
同样关心这个问题，希望能保持原有字体名称。
