### ISSUE TITLE
字号大于11时，部分汉字笔画显示异常

### ISSUE THREAD

**Issue by h1orz** [edward-p/Consolas-with-Yahei#2]
如图所示：
![20171009103107](https://user-images.githubusercontent.com/18734825/31323693-f073e1f0-acdd-11e7-8efd-8d1e44c42f26.png)
YaHei Consolas Hybrid没这个问题。😭

**Comment by edward-p** [comment]
能贴上你字体的设置和操作系统吗？

**Comment by h1orz** [comment]
不知是否是Win10引起的，我再试试别的机器看看。
font_face: 'Consolas'没错，😄

**Comment by edward-p** [comment]
@h1orz 好久没用win10撸过码了😂

**Comment by h1orz** [comment]
找了两台机器验证，确实有汉字显示异常的问题。
OS: Win10

**Comment by edward-p** [comment]
等我有时间再看看吧

**Comment by edward-p** [comment]
@h1orz 
应该是win10更新时又把字体替换回去了。。。

![capture](https://user-images.githubusercontent.com/7891089/31643483-5b8cd56e-b323-11e7-9e17-2f7ad4bfc4f5.PNG)
重新安装就能正常显示
![capture2](https://user-images.githubusercontent.com/7891089/31643495-6bc9a3ee-b323-11e7-977e-b734794e518f.PNG)
目前解决的办法有改名：https://github.com/wuqiling97/Consolas-with-Yahei
但是改了之后sublime好像就不能显示粗体斜体了，所以一起来寻求更好的解决办法吧,针对windows而言。
